# 1

Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [2]:
import numpy as np

In [10]:
a=np.array([3,5,7,9], dtype="int")
a

array([3, 5, 7, 9])

In [15]:
a.dtype

dtype('int32')

In [13]:
a.ndim

1

In [14]:
a.size

4

# 2
İki ve üç boyutlu arrayler oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [20]:
array2= np.array([[2,4,6],[1,2,3]])
array2

array([[2, 4, 6],
       [1, 2, 3]])

In [21]:
array3=np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[3,2,1]]])
array3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 2, 1]]])

In [22]:
array2.ndim

2

In [23]:
array3.ndim

3

In [24]:
array2.size

6

In [25]:
array3.size

12

In [27]:
np.shape(array2)

(2, 3)

In [28]:
np.shape(array3)

(2, 2, 3)

In [33]:
array2[1,1]

2

In [35]:
array2[0:2,2]

array([6, 3])

In [38]:
array3[1,0,2]

9

In [40]:
array3[1,1,0:3]

array([3, 2, 1])

# 3

Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturalım. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [12]:
array1d = np.array([1, 2, 3, 4, 5])


array2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


array3d = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     
                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]],
                     
                     [[19, 20, 21],
                      [22, 23, 24],
                      [25, 26, 27]]])


# 1D için
print(array1d[3])
print(array1d[2:5])
print(array1d[::2]) 
print("\n")

#2D için
print(array1d[4])
print(array2d[0, 1])
print(array2d[1:,:3])
print("\n")

#3D için
print(array3d[1])
print(array3d[0, 1])
print(array3d[:3, 1, ::-1])

4
[3 4 5]
[1 3 5]


5
2
[[4 5 6]
 [7 8 9]]


[[10 11 12]
 [13 14 15]
 [16 17 18]]
[4 5 6]
[[ 6  5  4]
 [15 14 13]
 [24 23 22]]


# 4

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [3]:
a=np.zeros((3,3),dtype="int")
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
b=np.ones((3,3),dtype="int")
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
np.concatenate((a,b),axis=0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
np.concatenate((a,b),axis=1)


array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])